package palmos;

public class Palm {
  public native static int AlmGetAlarm(int cardNo, int dbID, Integer refP);
  public native static int AlmSetAlarm(int cardNo, int dbID, int ref, int alarmSeconds, boolean quiet);
  public native static void CategoryCreateList(int db, int lst, int currentCategory, boolean showAll);
  public native static boolean CategoryEdit(int db, Short category);
  public native static int CategoryFind(int db, String name);
  public native static void CategoryFreeList(int db, int list);
  public native static void CategoryGetName(int db, int index, String name);
  public native static int CategoryGetNext(int db, int index);
  public native static void CategoryTruncateName(String name, int maxWidth);
  public native static void CategorySetTriggerLabel(int ctl, String name);
  public native static boolean CategorySelect(int db, int frm, int ctlID, int lstID, boolean title, Short categoryP, String categoryName);
  public native static void ClipboardAddItem(int format, Object ptr, int length);
  public native static int ClipboardGetItem(int format, Short length);
  public native static void CtlDrawControl(int ControlP);
  public native static void CtlEraseControl(int ControlP);
  public native static String CtlGetLabel(int ControlP);
  public native static int CtlGetValue(int ControlP);
  public native static boolean CtlHandleEvent(int ControlP, Event EventP);
  public native static void CtlHideControl(int ControlP);
  public native static void CtlHitControl(int ControlP);
  public native static boolean CtlEnabled(int ControlP);
  public native static void CtlSetEnabled(int ControlP, boolean enable);
  public native static void CtlSetLabel(int ControlP, String newLabel);
  public native static void CtlSetUsable(int ControlP, boolean usable);
  public native static void CtlSetValue(int ControlP, int newValue);
  public native static void CtlShowControl(int ControlP);
  public native static int DmArchiveRecord(int dbR, int index);
  public native static int DmAttachRecord(int dbR, Short atP, int newH, Integer oldHP);
  public native static int DmAttachResource(int dbR, int newH, int resType, int resID);
  public native static int DmCloseDatabase(int dbR);
  public native static int DmCreateDatabase(int cardNo, String nameP, int creator, int type, boolean resDB);
  public native static int DmCreateDatabaseFromImage(Object bufferP);
  public native static int DmDatabaseInfo(int cardNo, int dbID, String nameP, Short attributesP, Short versionP, Integer crDateP, Integer modDateP, Integer bckUpDateP, Integer modNumP, Integer appInfoIDP, Integer sortInfoIDP, Integer typeP, Integer creatorP);
  public native static int DmDatabaseSize(int cardNo, int dbID, Integer numRecordsP, Integer totalBytesP, Integer dataBytesP);
  public native static int DmDeleteDatabase(int cardNo, int dbID);
  public native static int DmDeleteRecord(int dbR, int index);
  public native static int DmDetachRecord(int dbR, int index, Integer oldHP);
  public native static int DmDetachResource(int dbR, int index, Integer oldHP);
  public native static int DmFindDatabase(int cardNo, String nameP);
  public native static int DmFindRecordByID(int dbR, int uniqueID, Short indexP);
  public native static int DmFindResource(int dbR, int resType, int resID, int findResH);
  public native static int DmFindResourceType(int dbR, int resType, int typeIndex);
  public native static int DmGetAppInfoID(int dbR);
  public native static int DmGetDatabase(int cardNo, int index);
  public native static int DmGetLastErr();
  public native static int DmGetNextDatabaseByTypeCreator(boolean newSearch, DmSearchState stateInfoP, int type, int creator, boolean onlyLatestVers, Short cardNoP, Integer dbIDP);
  public native static int DmGetRecord(int dbR, int index);
  public native static int DmGetResource(int type, int ID);
  public native static int DmGetResourceIndex(int dbR, int index);
  public native static int DmGet1Resource(int type, int ID);
  public native static int DmMoveCategory(int dbR, int toCategory, int fromCategory, boolean dirty);
  public native static int DmMoveRecord(int dbR, int from, int to);
  public native static int DmNewHandle(int dbR, int size);
  public native static int DmNextOpenDatabase(int currentP);
  public native static int DmNextOpenResDatabase(int dbR);
  public native static int DmNewRecord(int dbR, Short atP, int size);
  public native static int DmNewResource(int dbR, int resType, int resID, int size);
  public native static int DmNumDatabases(int cardNo);
  public native static int DmNumRecords(int dbR);
  public native static int DmNumRecordsInCategory(int dbR, int category);
  public native static int DmNumResources(int dbR);
  public native static int DmOpenDatabase(int cardNo, int dbID, int mode);
  public native static int DmOpenDatabaseByTypeCreator(int type, int creator, int mode);
  public native static int DmOpenDatabaseInfo(int dbR, Integer dbIDP, Short openCountP, Short modeP, Short cardNoP, Boolean resDBP);
  public native static int DmPositionInCategory(int dbR, int index, int category);
  public native static int DmQueryNextInCategory(int dbR, Short indexP, int category);
  public native static int DmQueryRecord(int dbR, int index);
  public native static int DmRecordInfo(int dbR, int index, Byte attrP, Integer uniqueIDP, Integer chunkIDP);
  public native static int DmResourceInfo(int dbR, int index, Integer resTypeP, Short resIDP, Integer chunkLocalIDP);
  public native static int DmReleaseRecord(int dbR, int index, boolean dirty);
  public native static int DmReleaseResource(int resourceH);
  public native static int DmRemoveRecord(int dbR, int index);
  public native static int DmRemoveResource(int dbR, int index);
  public native static int DmRemoveSecretRecords(int dbR);
  public native static int DmResetRecordStates(int dbR);
  public native static int DmResizeRecord(int dbR, int index, int newSize);
  public native static int DmResizeResource(int resourceH, int newSize);
  public native static int DmSearchRecord(int recH, Integer dbRP);
  public native static int DmSearchResource(int resType, int resId, int resH, Integer dbRP);
  public native static int DmSeekRecordInCategory(int dbR, Short indexP, int offset, int direction, int category);
  public native static int DmSet(Object recordP, int offset, int bytes, int value);
  public native static int DmSetDatabaseInfo(int cardNo, int dbID, String nameP, Short attributesP, Short versionP, Integer crDateP, Integer modDateP, Integer bckUpDateP, Integer modNumP, Integer appInfoIDP, Integer sortInfoIDP, Integer typeP, Integer creatorP);
  public native static int DmSetRecordInfo(int dbR, int index, Byte attrP, Integer uniqueIDP);
  public native static int DmSetResourceInfo(int dbR, int index, Integer resTypeP, Short resIDP);
  public native static int DmStrCopy(Object recordP, int offset, String srcP);
  public native static int DmWrite(Object recordP, int ofset, Object srcP, int bytes);
  public native static int DmWriteCheck(Object recordP, int ofset, int bytes);
  public native static void ErrDisplayFileLineMsg(String filename, int lineno, String msg);
  public native static void EvtAddEventToQueue(Event event);
  public native static void EvtCopyEvent(Event source, Event dest);
  public native static int EvtDequeuePenPoint(PointType retP);
  public native static int EvtDequeuePenStrokeInfo(PointType startPtP, PointType endPtP);
  public native static void EvtEnableGraffiti(boolean enable);
  public native static int EvtEnqueueKey(int ascii, int keycode, int modifiers);
  public native static int EvtFlushKeyQueue();
  public native static int EvtFlushNextPenStroke();
  public native static int EvtFlushPenQueue();
  public native static void EvtGetEvent(Event event, int timeout);
  public native static void EvtGetPen(Short pScreenX, Short pScreenY, Boolean pPenDown);
  public native static boolean EvtKeyQueueEmpty();
  public native static int EvtKeyQueueSize();
  public native static int EvtPenQueueSize();
  public native static int EvtProcessSoftKeyStroke(PointType startPtP, PointType endPtP);
  public native static int EvtResetAutoOffTimer();
  public native static int EvtWakeup();
  public native static void FindStrInStr(String strToSearch, String strToFind, Short posP);
  public native static int FldCalcFieldHeight(String chars, int maxWidth);
  public native static void FldCompactText(int fld);
  public native static void FldCopy(int fld);
  public native static void FldCut(int fld);
  public native static void FldDelete(int fld, int start, int end);
  public native static boolean FldDirty(int fld);
  public native static void FldDrawField(int fld);
  public native static void FldEraseField(int fld);
  public native static void FldFreeMemory(int fld);
  public native static void FldGetAttributes(int fld, FieldAttr attrP);
  public native static void FldGetBounds(int fld, Rectangle rect);
  public native static int FldGetFont(int fld);
  public native static int FldGetInsPtPosition(int fld);
  public native static int FldGetMaxChars(int fld);
  public native static int FldGetScrollPosition(int fld);
  public native static void FldGetSelection(int fld, Short startPosition, Short endPosition);
  public native static int FldGetTextAllocatedSize(int fld);
  public native static int FldGetTextHandle(int fld);
  public native static int FldGetTextHeight(int fld);
  public native static int FldGetTextLength(int fld);
  public native static String FldGetTextPtr(int fld);
  public native static int FldGetVisibleLines(int fld);
  public native static void FldGrabFocus(int fld);
  public native static boolean FldHandleEvent(int fld, Event EventP);
  public native static boolean FldInsert(int fld, String insertChars, int insertLen);
  public native static boolean FldMakeFullyVisible(int fld);
  public native static void FldPaste(int field);
  public native static void FldRecalculateField(int fld, boolean redraw);
  public native static void FldReleaseFocus(int fld);
  public native static boolean FldScrollable(int fld, int direction);
  public native static void FldScrollField(int fld, int linesToScroll, int direction);
  public native static void FldSendChangeNotification(int fld);
  public native static void FldSendHeightChangeNotification(int fld);
  public native static void FldSetAttributes(int fld, FieldAttr attrP);
  public native static void FldSetBounds(int fld, Rectangle rect);
  public native static void FldSetDirty(int fld, boolean dirty);
  public native static void FldSetFont(int fld, int fontID);
  public native static void FldSetInsPtPosition(int fld, int pos);
  public native static void FldSetMaxChars(int fld, int maxChars);
  public native static void FldSetScrollPosition(int fld, int pos);
  public native static void FldSetSelection(int fld, int startPosition, int endPosition);
  public native static void FldSetText(int fld, int textHandle, int offset, int size);
  public native static void FldSetTextAllocatedSize(int fld, int allocatedSize);
  public native static void FldSetTextHandle(int fld, int textHandle);
  public native static void FldSetTextPtr(int fld, String textP);
  public native static void FldSetUsable(int fld, boolean usable);
  public native static void FldUndo(int fld);
  public native static int FldWordWrap(String chars, int maxWidth);
  public native static int FntAverageCharWidth();
  public native static int FntBaseLine();
  public native static int FntCharHeight();
  public native static void FntCharsInWidth(String string, Short stringWidthP, Short stringLengthP, Boolean fitWithinWidth);
  public native static int FntCharsWidth(String pChars, int length);
  public native static int FntCharWidth(char ch);
  public native static int FntDescenderHeight();
  public native static int FntGetFont();
  public native static int FntGetFontPtr();
  public native static int FntLineHeight();
  public native static int FntLineWidth(String pChars, int length);
  public native static int FntSetFont(int fontID);
  public native static int FrmAlert(int alertId);
  public native static void FrmCloseAllForms();
  public native static void FrmCopyLabel(int frm, int labelID, String newLabel);
  public native static void FrmCopyTitle(int frm, String newTitle);
  public native static int FrmCustomAlert(int alertId, String s1, String s2, String s3);
  public native static void FrmDeleteForm(int frm);
  public native static boolean FrmDispatchEvent(Event eventP);
  public native static int FrmDoDialog(int frm);
  public native static void FrmDrawForm(int frm);
  public native static void FrmEraseForm(int frm);
  public native static int FrmGetActiveForm();
  public native static int FrmGetActiveFormID();
  public native static byte FrmGetControlGroupSelection(int frm, int groupNum);
  public native static int FrmGetControlValue(int frm, int objIndex);
  public native static int FrmGetFirstForm();
  public native static int FrmGetFocus(int frm);
  public native static void FrmGetFormBounds(int frm, Rectangle r);
  public native static int FrmGetFormId(int frm);
  public native static int FrmGetFormPtr(int formId);
  public native static int FrmGetGadgetData(int frm, int objIndex);
  public native static String FrmGetLabel(int frm, int labelID);
  public native static int FrmGetNumberOfObjects(int frm);
  public native static void FrmGetObjectBounds(int frm, int ObjIndex, Rectangle r);
  public native static int FrmGetObjectId(int frm, int objIndex);
  public native static int FrmGetObjectIndex(int frm, int objID);
  public native static void FrmGetObjectPosition(int frm, int objIndex, Short x, Short y);
  public native static int FrmGetObjectPtr(int frm, int objIndex);
  public native static int FrmGetObjectType(int frm, int objIndex);
  public native static String FrmGetTitle(int frm);
  public native static boolean FrmGetUserModifiedState(int frm);
  public native static int FrmGetWindowHandle(int frm);
  public native static void FrmGotoForm(int formId);
  public native static boolean FrmHandleEvent(int frm, Event event);
  public native static void FrmHelp(int helpMsgId);
  public native static void FrmHideObject(int frm, int objIndex);
  public native static int FrmInitForm(int rscID);
  public native static void FrmPopupForm(int formId);
  public native static void FrmReturnToForm(int formId);
  public native static void FrmSaveAllForms();
  public native static void FrmSetActiveForm(int frm);
  public native static void FrmSetCategoryLabel(int frm, int objIndex, String newLabel);
  public native static void FrmSetControlGroupSelection(int frm, int groupNum, int controlID);
  public native static void FrmSetControlValue(int frm, int objIndex, int newValue);
  public native static void FrmSetFocus(int frm, int objIndex);
  public native static void FrmSetGadgetData(int frm, int objIndex, Object data);
  public native static void FrmSetNotUserModified(int frm);
  public native static void FrmSetObjectPositon(int frm, int objIndex, int x, int y);
  public native static void FrmSetTitle(int frm, String newTitle);
  public native static void FrmShowObject(int frm, int objIndex);
  public native static void FrmUpdateScrollers(int frm, int upIndex, int downIndex, boolean scrollableUp, boolean scrollableDown);
  public native static void FrmUpdateForm(int formId, int updateCode);
  public native static boolean FrmVisible(int frm);
  public native static int FtrGet(int creator, int featureNum, Integer valueP);
  public native static int FtrGetByIndex(int index, boolean romTable, Integer creatorP, Short numP, Integer valueP);
  public native static int FtrSet(int creator, int featureNum, int newValue);
  public native static int FtrUnregister(int creator, int featureNum);
  public native static int GrfAddMacro(String nameP, Object macroDataP, int dataLen);
  public native static int GrfAddPoint(PointType ptP);
  public native static int GrfCleanState();
  public native static int GrfDeleteMacro(int index);
  public native static int GrfFindBranch(int flags);
  public native static int GrfFilterPoints();
  public native static int GrfFlushPoints();
  public native static int GrfGetAndExpandMacro(String nameP, Object macroDataP, Short dataLenP);
  public native static int GrfGetGlyphMapping(int glyphID, Short flagsP, Object dataPtrP, Short dataLenP, Short uncertainLenP);
  public native static int GrfGetMacro(String nameP, Object macroDataP, Short dataLenP);
  public native static int GrfGetMacroName(int index, String nameP);
  public native static int GrfGetNumPoints(Short numPtsP);
  public native static int GrfGetPoint(int index, PointType pointP);
  public native static int GrfGetState(Boolean capsLockP, Boolean numLockP, Short tempShiftP, Boolean autoShiftedP);
  public native static int GrfInitState();
  public native static int GrfProcessStroke(PointType startPtP, PointType endPtP, boolean upShift);
  public native static int GrfSetState(boolean capsLock, boolean numLock, boolean upperShift);
  public native static void GsiEnable(boolean enableIt);
  public native static boolean GsiEnabled();
  public native static void GsiInitialize();
  public native static void GsiSetLocation(int x, int y);
  public native static void GsiSetShiftState(int lockFlags, int tempShift);
  public native static void InsPtEnable(boolean enableIt);
  public native static boolean InsPtEnabled();
  public native static int InsPtGetHeight();
  public native static void InsPtGetLocation(Short x, Short y);
  public native static void InsPtSetHeight(int height);
  public native static void InsPtSetLocation(int x, int y);
  public native static int KeyCurrentState();
  public native static int KeyRates(boolean set, Short initDelayP, Short periodP, Short doubleTapDelayP, Boolean queueAheadP);
  public native static void LstDrawList(int ListP);
  public native static void LstEraseList(int ListP);
  public native static int LstGetNumberOfItems(int ListP);
  public native static int LstGetSelection(int ListP);
  public native static String LstGetSelectionText(int ListP, int itemNum);
  public native static boolean LstHandleEvent(int ListP, Event pEvent);
  public native static void LstMakeItemVisible(int ListP, int itemNum);
  public native static int LstPopupList(int ListP);
  public native static void LstSetHeight(int ListP, int visibleItems);
  public native static void LstSetPosition(int ListP, int x, int y);
  public native static void LstSetSelection(int ListP, int itemNum);
  public native static void LstSetTopItem(int ListP, int itemNum);
  public native static int MemCardInfo(int cardNo, StringBuffer cardNameP, StringBuffer manufNamP, Short versionP, Integer crDateP, Integer romSizeP, Integer ramSizeP, Integer freeBytesP);
  public native static int MemChunkFree(int chunkDataP);
  public native static int MemDebugMode();
  public native static boolean MemHandleDataStorage(int h);
  public native static int MemHandleCardNo(int h);
  public native static int MemHandleFree(int h);
  public native static int MemHandleHeapID(int h);
  public native static int MemHandleLock(int h);
  public native static int MemHandleNew(int size);
  public native static int MemHandleResize(int h, int newSize);
  public native static int MemHandleSize(int h);
  public native static int MemHandleToLocalID(int h);
  public native static int MemHandleUnlock(int h);
  public native static int MemHeapCheck(int heapID);
  public native static int MemHeapCompact(int heapID);
  public native static boolean MemHeapDynamic(int heapID);
  public native static int MemHeapFlags(int heapID);
  public native static int MemHeapFreeBytes(int heapID, Integer freeP, Integer maxP);
  public native static int MemHeapID(int cardNo, int heapIndex);
  public native static int MemHeapScramble(int heapID);
  public native static int MemHeapSize(int heapID);
  public native static int MemLocalIDKind(int local);
  public native static int MemLocalIDToGlobal(int local, int cardNo);
  public native static int MemLocalIDToLockedPtr(int local, int cardNo);
  public native static int MemLocalIDToPtr(int local, int cardNo);
  public native static int MemMove(int dstP, int srcP, int numBytes);
  public native static int MemNumCards();
  public native static int MemNumHeaps(int cardNo);
  public native static int MemNumRAMHeaps(int cardNo);
  public native static int MemPtrCardNo(int chunkP);
  public native static boolean MemPtrDataStorage(int p);
  public native static int MemPtrFree(int p);
  public native static int MemPtrHeapID(int p);
  public native static int MemPtrToLocalID(int chunkP);
  public native static int MemPtrNew(int size);
  public native static int MemPtrRecoverHandle(int p);
  public native static int MemPtrResize(int p, int newSize);
  public native static int MemSet(int dstP, int numBytes, int value);
  public native static int MemSetDebugMode(int flags);
  public native static int MemPtrSize(int p);
  public native static int MemPtrUnlock(int p);
  public native static int MemStoreInfo(int cardNo, int storeNumber, Short versionP, Short flagsP, StringBuffer nameP, Integer crDateP, Integer bckUpDateP, Integer heapListOffsetP, Integer initCodeOffset1P, Integer initCodeOffset2P, Integer databaseDirIDP);
  public native static void MenuDispose(int MenuP);
  public native static void MenuDrawMenu(int MenuP);
  public native static void MenuEraseStatus(int MenuP);
  public native static int MenuGetActiveMenu();
  public native static boolean MenuHandleEvent(int MenuP, Event event, Short error);
  public native static int MenuInit(int resourceId);
  public native static int MenuSetActiveMenu(int MenuP);
  public native static void AbtShowAbout(int creator);
  public native static int Crc16CalcBlock(Object bufP, int count, int crc);
  public native static boolean DayHandleEvent(DaySelector pSelector, Event pEvent);
  public native static int PenCalibrate(PointType digTopLeftP, PointType digBotRightP, PointType scrTopLeftP, PointType scrBotRightP);
  public native static int PenResetCalibration();
  public native static boolean PrefGetAppPreferences(int type, int version, Object prefs, int prefsSize);
  public native static void PrefGetPreferences(SystemPreferences p);
  public native static int PrefOpenPreferenceDB();
  public native static void PrefSetAppPreferences(int type, int version, Object prefs, int prefsSize);
  public native static void PrefSetPreferences(SystemPreferences p);
  public native static int SerClearErr(int refNum);
  public native static int SerClose(int refNum);
  public native static int SerGetSettings(int refNum, SerSettings settingsP);
  public native static int SerGetStatus(int refNum, Boolean ctsOnP, Boolean dtsOnP);
  public native static int SerOpen(int refNum, int port, int baud);
  public native static int SerReceive(int refNum, Object bufP, int bytes, int timeout);
  public native static int SerReceiveCheck(int refNum, Integer numBytesP);
  public native static void SerReceiveFlush(int refNum, int timeout);
  public native static int SerReceiveWait(int refNum, int bytes, int timeout);
  public native static int SerSend(int refNum, Object bufP, int size);
  public native static int SerSend(int refNum, int bufP, int size);
  public native static int SerSendWait(int refNum, int timeout);
  public native static int SerSetReceiveBuffer(int refNum, Object bufP, int bufSize);
  public native static int SerSetSettings(int refNum, SerSettings settingsP);
  public native static int SlkClose();
  public native static int SlkCloseSocket(int socket);
  public native static int SlkFlushSocket(int socket, int timeout);
  public native static int SlkOpen();
  public native static int SlkOpenSocket(int libRefNum, Short socketP, boolean staticSocket);
  public native static int SlkReceivePacket(int socket, boolean andOtherSockets, SlkPktHeader headerP, Object bodyP, int bodySize, int timeout);
  public native static int SlkSocketRefNum(int socket, Short refNumP);
  public native static int SlkSocketSetTimeout(int socket, int timeout);
  public native static int SndDoCmd(Object chanP, SndCommand cmdP, boolean noWait);
  public native static void SndGetDefaultVolume(Short alarmAmpP, Short sysAmpP, Short defAmpP);
  public native static void SndPlaySystemSound(int beepID);
  public native static void SndSetDefaultVolume(Short alarmAmpP, Short sysAmpP, Short defAmpP);
  public native static int StrAToI(String str);
  public native static int StrCaselessCompare(String s1, String s2);
  public native static int StrCompare(String s1, String s2);
  public native static int StrLen(String str);
  public native static int SysAppLaunch(int cardNo, int dbID, int launchFlags, int cmd, Object cmpPBP, Integer resultP);
  public native static int SysBatteryInfo(boolean set, Short warnThresholdP, Short criticalThresholdP, Short maxTicksP, Short kindP, Boolean pluggedIn);
  public native static int SysBroadcastActionCode(int cmd, Object cmdPBP);
  public native static void SysCopyStringResource(String string, int theID);
  public native static int SysCurAppDatabase(Short cardNoP, Integer dbIDP);
  public native static int SysFormPointerArrayToStrings(String c, int stringCount);
  public native static boolean SysHandleEvent(Event eventP);
  public native static void SysKeyboardDialog();
  public native static int SysLibFind(String nameP, Short refNumP);
  public native static int SysRandom(int newSeed);
  public native static void SysReset();
  public native static int SysSetAutoOffTime(int seconds);
  public native static int SysTaskDelay(int delay);
  public native static int SysUIAppSwitch(int cardNo, int dbID, int cmd, Object cmdPBP);
  public native static void TblDrawTable(int table);
  public native static boolean TblEditing(int table);
  public native static void TblEraseTable(int table);
  public native static boolean TblFindRowData(int table, int data, Short rowP);
  public native static boolean TblFindRowID(int table, int id, Short rowP);
  public native static void TblGetBounds(int table, Rectangle r);
  public native static int TblGetColumnSpacing(int table, int column);
  public native static int TblGetColumnWidth(int table, int column);
  public native static int TblGetCurrentField(int table);
  public native static void TblGetItemBounds(int table, int row, int column, Rectangle r);
  public native static int TblGetItemInt(int table, int row, int column);
  public native static int TblGetLastUsableRow(int table);
  public native static int TblGetNumberOfRows(int table);
  public native static int TblGetRowData(int table, int row);
  public native static int TblGetRowHeight(int table, int row);
  public native static int TblGetRowID(int table, int row);
  public native static boolean TblGetSelection(int table, Short rowP, Short columnP);
  public native static void TblGrabFocus(int table, int row, int column);
  public native static boolean TblHandleEvent(int table, Event event);
  public native static void TblInsertRow(int table, int row);
  public native static void TblMarkRowInvalid(int table, int row);
  public native static void TblMarkTableInvalid(int table);
  public native static void TblRedrawTable(int table);
  public native static void TblReleaseFocus(int table);
  public native static void TblRemoveRow(int table, int row);
  public native static boolean TblRowInvalid(int table, int row);
  public native static boolean TblRowSelectable(int table, int row);
  public native static boolean TblRowUsable(int table, int row);
  public native static void TblSelectItem(int table, int row, int column);
  public native static void TblSetColumnSpacing(int table, int column, int spacing);
  public native static void TblSetColumnUsable(int table, int column, boolean usable);
  public native static void TblSetColumnWidth(int table, int column, int width);
  public native static void TblSetItemInt(int table, int row, int column, int value);
  public native static void TblSetItemPtr(int table, int row, int column, Object value);
  public native static void TblSetItemStyle(int table, int row, int column, int type);
  public native static void TblSetRowData(int table, int row, int data);
  public native static void TblSetRowHeight(int table, int row, int height);
  public native static void TblSetRowID(int table, int row, int id);
  public native static void TblSetRowSelectable(int table, int row, boolean selectable);
  public native static void TblSetRowUsable(int table, int row, boolean usable);
  public native static void TblUnhighlightSelection(int table);
  public native static void DateAdjust(Date dateP, int adjustment);
  public native static void DateDaysToDate(int days, Date dateP);
  public native static void DateSecondsToDate(int seconds, Date dateP);
  public native static void DateToAscii(int months, int days, int years, int dateFormat, StringBuffer pString);
  public native static int DateToDays(int date);
  public native static void DateToDOWDMFormat(int months, int days, int years, int dateFormat, StringBuffer pString);
  public native static int DayOfMonth(int month, int day, int year);
  public native static int DayOfWeek(int month, int day, int year);
  public native static int DaysInMonth(int month, int year);
  public native static boolean SelectDay(Short month, Short day, Short year, String title);
  public native static void TimAdjust(DateTime dateTimeP, int adjustment);
  public native static int TimDateTimeToSeconds(DateTime dateTimeP);
  public native static int TimGetSeconds();
  public native static int TimGetTicks();
  public native static void TimSecondsToDateTime(int seconds, DateTime dateTimeP);
  public native static void TimSetSeconds(int seconds);
  public native static void TimeToAscii(int hours, int minutes, int timeFormat, String pString);
  public native static void WinAddWindow(int winHandle);
  public native static void WinClipRectangle(Rectangle r);
  public native static void WinCopyRectangle(int srcWin, int dstWin, Rectangle srcRect, int destX, int destY, int mode);
  public native static int WinCreateWindow(Rectangle bounds, int frame, boolean modal, boolean focusable, Short error);
  public native static int WinCreateOffscreenWindow(int width, int height, int format, Short error);
  public native static void WinDeleteWindow(int winHandle, boolean eraseIt);
  public native static void WinDisableWindow(int winHandle);
  public native static void WinDisplayToWindowPt(Short extentX, Short extentY);
  public native static void WinDrawBitmap(int bitmapP, int x, int y);
  public native static void WinDrawChars(String chars, int len, int x, int y);
  public native static void WinDrawGrayLine(int x1, int y1, int x2, int y2);
  public native static void WinDrawGrayRectangleFrame(int frame, Rectangle r);
  public native static void WinDrawInvertedChars(String chars, int len, int x, int y);
  public native static void WinDrawLine(int x1, int y1, int x2, int y2);
  public native static void WinDrawRectangle(Rectangle r, int cornerDiam);
  public native static void WinDrawRectangleFrame(int frame, Rectangle r);
  public native static void WinDrawWindowFrame();
  public native static void WinEnableWindow(int winHandle);
  public native static void WinEraseChars(String chars, int len, int x, int y);
  public native static void WinEraseLine(int x1, int y1, int x2, int y2);
  public native static void WinEraseRectangle(Rectangle r, int cornerDiam);
  public native static void WinEraseRectangleFrame(int frame, Rectangle r);
  public native static void WinEraseWindow();
  public native static void WinFillLine(int x1, int y1, int x2, int y2);
  public native static void WinFillRectangle(Rectangle r, int cornerDiam);
  public native static int WinGetActiveWindow();
  public native static void WinGetClip(Rectangle r);
  public native static void WinGetDisplayExtent(Short extentX, Short extentY);
  public native static int WinGetDisplayWindow();
  public native static int WinGetDrawWindow();
  public native static int WinGetFirstWindow();
  public native static void WinGetFramesRectangle(int frame, Rectangle r, Rectangle obscuredRect);
  public native static void WinGetWindowBounds(Rectangle r);
  public native static void WinGetWindowExtent(Short extentX, Short extentY);
  public native static void WinGetWindowFrameRect(int winHandle, Rectangle r);
  public native static void WinInitializeWindow(int winHandle);
  public native static void WinInvertChars(String chars, int len, int x, int y);
  public native static void WinInvertLine(int x1, int y1, int x2, int y2);
  public native static void WinInvertRectangle(Rectangle r, int cornerDiam);
  public native static void WinInvertRectangleFrame(int frame, Rectangle r);
  public native static boolean WinModal(int winHandle);
  public native static void WinRemoveWindow(int winHandle);
  public native static void WinResetClip();
  public native static void WinRestoreBits(int winHandle, int destX, int destY);
  public native static int WinSaveBits(Rectangle sourceP, Short error);
  public native static void WinScrollRectangle(Rectangle r, int direction, int distance, Rectangle vacated);
  public native static void WinSetActiveWindow(int winHandle);
  public native static void WinSetClip(Rectangle r);
  public native static int WinSetDrawWindow(int winHandle);
  public native static int WinSetUnderlineMode(int mode);
  public native static void WinWindowToDisplayPt(Short extentX, Short extentY);
}
